"""Persistent Multi-Farmer Registry & Seed Profiles for 5 realistic Andhra Pradesh farms."""
from __future__ import annotations

from typing import Any, Dict, List

FARMER_REGISTRY: Dict[int, Dict[str, Any]] = {
    1: {
        "id": 1,
        "farmer_name": "Ramesh Kumar",
        "farmer_name_te": "రమేష్ కుమార్",
        "farmer_name_hi": "रमेश कुमार",
        "village": "Kankipadu",
        "village_te": "కంకిపాడు",
        "village_hi": "कंकिपाडु",
        "crop": "Rice",
        "crop_variety": "Rice (BPT-5204)",
        "crop_te": "వరి (BPT-5204) · పెరుగుదల దశ (35 రోజులు)",
        "crop_hi": "धान (BPT-5204) · वानस्पतिक अवस्था (35 दिन)",
        "growth_stage": "Vegetative",
        "crop_age_days": 35,
        "area_acres": 3.5,
        "lat": 16.4337,
        "lon": 80.7669,
        "sensor_mode": "LIVE_ESP32_GPIO34",
        "device_id": "esp32_zone_01",
        "default_moisture": 18.5,
        "critical_threshold": 30.0,
        "default_precip_prob": 5,
        "status_code": "CRITICAL_DEFICIT",
        "risk_badge": "CRITICAL_DEFICIT (18.5% Moisture)",
        "pest_or_disease_risk": "Low",
        "health_score": 42,
        "action_type": "IRRIGATION_DISPATCH",
        "action_depth_mm": 15.0,
        "fleet_unit": "MAVLink Irrigation Valve V1 + Drone UAV-Alpha (0.8 km away)",
        "chem_defaults": {
            "soil_ph": 6.72,
            "soil_temperature": 27.8,
            "nitrogen": 31.4,
            "phosphorus": 19.6,
            "potassium": 184.0,
        },
    },
    2: {
        "id": 2,
        "farmer_name": "Suresh Reddy",
        "farmer_name_te": "సురేష్ రెడ్డి",
        "farmer_name_hi": "सुरेश रेड्डी",
        "village": "Guntur",
        "village_te": "గుంటూరు",
        "village_hi": "गुंटूर",
        "crop": "Cotton (Bt-II)",
        "crop_variety": "Cotton (Bt-II)",
        "crop_te": "పత్తి (Bt-II) · పూత దశ (58 రోజులు)",
        "crop_hi": "कपास (Bt-II) · फूल आने की अवस्था (58 दिन)",
        "growth_stage": "Flowering",
        "crop_age_days": 58,
        "area_acres": 5.0,
        "lat": 16.3067,
        "lon": 80.4365,
        "sensor_mode": "SIMULATED_NODE",
        "device_id": "sim_node_guntur_02",
        "default_moisture": 42.0,
        "critical_threshold": 28.0,
        "default_precip_prob": 10,
        "status_code": "OPTIMAL",
        "risk_badge": "OPTIMAL (42.0% Moisture) · Moderate Bollworm",
        "pest_or_disease_risk": "Moderate Bollworm",
        "health_score": 89,
        "action_type": "PEST_SCOUTING_ADVISORY",
        "action_depth_mm": 0.0,
        "fleet_unit": "Rover UGV-02 (Standby at Guntur Hub · 1.4 km)",
        "chem_defaults": {
            "soil_ph": 6.95,
            "soil_temperature": 28.4,
            "nitrogen": 34.2,
            "phosphorus": 21.8,
            "potassium": 196.0,
        },
    },
    3: {
        "id": 3,
        "farmer_name": "Venkat Rao",
        "farmer_name_te": "వెంకట్ రావు",
        "farmer_name_hi": "वेंकट राव",
        "village": "Tenali",
        "village_te": "తెనాలి",
        "village_hi": "तेनाली",
        "crop": "Chilli (Teja)",
        "crop_variety": "Chilli (Teja)",
        "crop_te": "మిర్చి (తేజ) · పెరుగుదల దశ (45 రోజులు)",
        "crop_hi": "मिर्च (तेजा) · वानस्पतिक अवस्था (45 दिन)",
        "growth_stage": "Vegetative",
        "crop_age_days": 45,
        "area_acres": 2.0,
        "lat": 16.2430,
        "lon": 80.6400,
        "sensor_mode": "SIMULATED_NODE",
        "device_id": "sim_node_tenali_03",
        "default_moisture": 14.2,
        "critical_threshold": 26.0,
        "default_precip_prob": 8,
        "status_code": "CRITICAL_DEFICIT",
        "risk_badge": "CRITICAL_DEFICIT (14.2% Moisture) · Fungal Risk High",
        "pest_or_disease_risk": "Fungal Risk High",
        "health_score": 34,
        "action_type": "DRIP_IRRIGATION_AND_FUNGAL_GUARD",
        "action_depth_mm": 12.0,
        "fleet_unit": "Drip Valve Zone-3 + Multispectral Drone UAV-Beta (1.1 km)",
        "chem_defaults": {
            "soil_ph": 6.55,
            "soil_temperature": 29.1,
            "nitrogen": 29.0,
            "phosphorus": 17.5,
            "potassium": 178.0,
        },
    },
    4: {
        "id": 4,
        "farmer_name": "Priya Sharma",
        "farmer_name_te": "ప్రియా శర్మ",
        "farmer_name_hi": "प्रिया शर्मा",
        "village": "Vijayawada",
        "village_te": "విజయవాడ",
        "village_hi": "विजयवाड़ा",
        "crop": "Maize",
        "crop_variety": "Maize (Hybrid DHM-117)",
        "crop_te": "మొక్కజొన్న · విత్తే దశ (Sowing)",
        "crop_hi": "मक्का · बुवाई अवस्था (Sowing)",
        "growth_stage": "Sowing",
        "crop_age_days": 4,
        "area_acres": 4.0,
        "lat": 16.5062,
        "lon": 80.6480,
        "sensor_mode": "SIMULATED_NODE",
        "device_id": "sim_node_vja_04",
        "default_moisture": 55.0,
        "critical_threshold": 25.0,
        "default_precip_prob": 75,
        "status_code": "RAIN_DELAY",
        "risk_badge": "RAIN_DELAY (55.0% Moisture · 75% Incoming Rain)",
        "pest_or_disease_risk": "Waterlogging / Seed Washout Risk",
        "health_score": 76,
        "action_type": "DELAY_SOWING_AND_IRRIGATION",
        "action_depth_mm": 0.0,
        "fleet_unit": "Seed-Drill Rover UGV-01 (Held at Depot due to 75% Rain)",
        "chem_defaults": {
            "soil_ph": 6.84,
            "soil_temperature": 26.2,
            "nitrogen": 33.5,
            "phosphorus": 22.1,
            "potassium": 191.0,
        },
    },
    5: {
        "id": 5,
        "farmer_name": "Lakshmi Bai",
        "farmer_name_te": "లక్ష్మీ బాయి",
        "farmer_name_hi": "लक्ष्मी बाई",
        "village": "Nandigama",
        "village_te": "నందిగామ",
        "village_hi": "नंदिगामा",
        "crop": "Groundnut",
        "crop_variety": "Groundnut (Kadiri-6)",
        "crop_te": "వేరుశనగ · కాయ అభివృద్ధి దశ (Pod Development)",
        "crop_hi": "मूंगफली · फली विकास अवस्था (Pod Development)",
        "growth_stage": "Pod Development",
        "crop_age_days": 62,
        "area_acres": 2.5,
        "lat": 16.7725,
        "lon": 80.2859,
        "sensor_mode": "SIMULATED_NODE",
        "device_id": "sim_node_nandigama_05",
        "default_moisture": 24.0,
        "critical_threshold": 28.0,
        "default_precip_prob": 12,
        "status_code": "DRY_WARNING",
        "risk_badge": "DRY_WARNING (24.0% Moisture)",
        "pest_or_disease_risk": "Low",
        "health_score": 61,
        "action_type": "IRRIGATION_DISPATCH",
        "action_depth_mm": 10.0,
        "fleet_unit": "Sprinkler Line Z5 + Soil Rover UGV-03 (2.1 km)",
        "chem_defaults": {
            "soil_ph": 6.64,
            "soil_temperature": 28.0,
            "nitrogen": 30.2,
            "phosphorus": 20.4,
            "potassium": 188.0,
        },
    },
}

SHARED_ROBOTICS_FLEET: List[Dict[str, Any]] = [
    {
        "unit_id": "UAV-ALPHA",
        "name": "Multispectral Drone Alpha (NDVI + Thermal)",
        "type": "DRONE",
        "assigned_zone": "Kankipadu / Tenali Corridor",
        "servicing_farmers": ["Ramesh Kumar (#1)", "Venkat Rao (#3)"],
        "status": "STANDBY_READY",
        "battery_pct": 94,
        "protocol": "MAVLink 2.0 UDP:14550",
    },
    {
        "unit_id": "UGV-ROVER-01",
        "name": "Autonomous Soil & Seed Rover 01",
        "type": "ROVER",
        "assigned_zone": "Vijayawada / Nandigama Sector",
        "servicing_farmers": ["Priya Sharma (#4)", "Lakshmi Bai (#5)"],
        "status": "RAIN_HOLD",
        "battery_pct": 88,
        "protocol": "ROS2 / MQTT farmwise/ugv01",
    },
    {
        "unit_id": "UGV-ROVER-02",
        "name": "Proximal Bollworm Scout Rover 02",
        "type": "ROVER",
        "assigned_zone": "Guntur Cotton Belt",
        "servicing_farmers": ["Suresh Reddy (#2)"],
        "status": "PATROLLING",
        "battery_pct": 79,
        "protocol": "ROS2 / MQTT farmwise/ugv02",
    },
    {
        "unit_id": "VALVE-MESH-AP",
        "name": "LoRaWAN / MAVLink Smart Irrigation Valve Cluster",
        "type": "ACTUATOR",
        "assigned_zone": "All 5 Registered Villages",
        "servicing_farmers": ["All 5 Farms"],
        "status": "ARMED",
        "battery_pct": 100,
        "protocol": "MAV_CMD_DO_SET_ACTUATOR",
    },
]


def get_farmer_meta(farmer_id: int) -> Dict[str, Any]:
    return dict(FARMER_REGISTRY.get(int(farmer_id), FARMER_REGISTRY[1]))


def list_all_farmer_metas() -> List[Dict[str, Any]]:
    return [dict(FARMER_REGISTRY[k]) for k in sorted(FARMER_REGISTRY.keys())]
